######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Lova | Personal blog template"
theme = "lova-hugo"
summaryLength = "10"
pagination.pagerSize = 6
disqusShortname = ""
